version: "3.7"

services:
  app:
    image: golang:1.17-alpine
    build: .
    ports:
      - 9090:9090
    working_dir: /app
    volumes:
      - videos:/app/static/
    command: /video_upload


volumes:
  videos:
